[package]
name = "kovi-plugin-cmd"
version = "0.1.0"
edition = "2021"
keywords = ["kovi", "kovi-plugin"]
license = "MPL-2.0"
authors = ["Threkork <threkork@hotmail.com>"]

[dependencies]
kovi = ">=0.11.5"
serde = { version = "1", features = ["derive"] }
sysinfo = "0.33.0"
