[package]
name = "kovi-plugin-expand-lagrange"
version = "0.1.0"
edition = "2021"
keywords = ["kovi", "kovi-plugin", "kovi-expand"]
description = "Kovi 的 Lagrange Api拓展。"
license = "MPL-2.0"
authors = ["Threkork <threkork@hotmail.com>"]

[dependencies]
kovi = ">= 0.8.2"
